import { Department, Employee, Project, Task, User, NotificationItem, ActivityLog, SystemSettings } from '../src/types';

export const initialDepartments: Department[] = [
  {
    id: 'dept-1',
    name: 'Engineering & Technology',
    code: 'ENG',
    description: 'Core software development, cloud infrastructure, AI models, and cybersecurity.',
    headName: 'Dr. Marcus Vance',
    headEmail: 'marcus.vance@enterprise.ai',
    budget: 450000,
    location: 'Building A, Floor 4',
    color: '#3B82F6',
    createdAt: '2024-01-15',
  },
  {
    id: 'dept-2',
    name: 'Product & Design',
    code: 'PROD',
    description: 'Product lifecycle management, UX/UI research, design systems, and roadmaps.',
    headName: 'Elena Rostova',
    headEmail: 'elena.rostova@enterprise.ai',
    budget: 280000,
    location: 'Building A, Floor 3',
    color: '#8B5CF6',
    createdAt: '2024-01-15',
  },
  {
    id: 'dept-3',
    name: 'Global Marketing & Brand',
    code: 'MKT',
    description: 'Enterprise brand campaigns, customer acquisition, product marketing, and PR.',
    headName: 'Sophia Chang',
    headEmail: 'sophia.chang@enterprise.ai',
    budget: 320000,
    location: 'Building B, Floor 2',
    color: '#EC4899',
    createdAt: '2024-02-01',
  },
  {
    id: 'dept-4',
    name: 'Enterprise Sales',
    code: 'SALES',
    description: 'Enterprise pipeline, B2B deal closing, strategic client partnerships.',
    headName: 'David Sterling',
    headEmail: 'david.sterling@enterprise.ai',
    budget: 390000,
    location: 'Building B, Floor 3',
    color: '#10B981',
    createdAt: '2024-02-01',
  },
  {
    id: 'dept-5',
    name: 'Human Resources & Talent',
    code: 'HR',
    description: 'Talent recruitment, compensation, employee wellness, and cultural initiatives.',
    headName: 'Rachel Green',
    headEmail: 'rachel.green@enterprise.ai',
    budget: 160000,
    location: 'Building C, Floor 1',
    color: '#F59E0B',
    createdAt: '2024-01-10',
  },
  {
    id: 'dept-6',
    name: 'Finance & Operations',
    code: 'FIN',
    description: 'Financial forecasting, compliance, procurement, and administrative operations.',
    headName: 'Arthur Pendelton',
    headEmail: 'arthur.p@enterprise.ai',
    budget: 240000,
    location: 'Building C, Floor 2',
    color: '#06B6D4',
    createdAt: '2024-01-10',
  },
];

export const initialEmployees: Employee[] = [
  {
    id: 'emp-1',
    name: 'Alexander Wright',
    email: 'alexander.wright@enterprise.ai',
    phone: '+1 (555) 234-5671',
    departmentId: 'dept-1',
    departmentName: 'Engineering & Technology',
    role: 'Principal Cloud Architect',
    status: 'Active',
    salary: 165000,
    joinDate: '2022-03-15',
    skills: ['Kubernetes', 'Go', 'AWS', 'System Architecture', 'PostgreSQL'],
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
    performanceScore: 94,
  },
  {
    id: 'emp-2',
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@enterprise.ai',
    phone: '+1 (555) 345-6782',
    departmentId: 'dept-1',
    departmentName: 'Engineering & Technology',
    role: 'Lead AI Engineer',
    status: 'Active',
    salary: 155000,
    joinDate: '2022-08-01',
    skills: ['Python', 'Gemini API', 'PyTorch', 'Vector Databases', 'LangChain'],
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=256&q=80',
    performanceScore: 98,
  },
  {
    id: 'emp-3',
    name: 'Michael Torres',
    email: 'michael.torres@enterprise.ai',
    phone: '+1 (555) 456-7893',
    departmentId: 'dept-1',
    departmentName: 'Engineering & Technology',
    role: 'Senior Full Stack Developer',
    status: 'Active',
    salary: 135000,
    joinDate: '2023-01-10',
    skills: ['React', 'TypeScript', 'Node.js', 'TailwindCSS', 'GraphQL'],
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
    performanceScore: 89,
  },
  {
    id: 'emp-4',
    name: 'Elena Rostova',
    email: 'elena.rostova@enterprise.ai',
    phone: '+1 (555) 567-8904',
    departmentId: 'dept-2',
    departmentName: 'Product & Design',
    role: 'VP of Product Management',
    status: 'Active',
    salary: 175000,
    joinDate: '2021-06-20',
    skills: ['Roadmapping', 'User Research', 'Data Analytics', 'Agile Scrum'],
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=256&q=80',
    performanceScore: 96,
  },
  {
    id: 'emp-5',
    name: 'Liam Chen',
    email: 'liam.chen@enterprise.ai',
    phone: '+1 (555) 678-9015',
    departmentId: 'dept-2',
    departmentName: 'Product & Design',
    role: 'Senior Product Designer',
    status: 'Remote',
    salary: 120000,
    joinDate: '2023-04-12',
    skills: ['Figma', 'Design Systems', 'Micro-interactions', 'Prototyping'],
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
    performanceScore: 91,
  },
  {
    id: 'emp-6',
    name: 'Sophia Chang',
    email: 'sophia.chang@enterprise.ai',
    phone: '+1 (555) 789-0126',
    departmentId: 'dept-3',
    departmentName: 'Global Marketing & Brand',
    role: 'Head of Growth Marketing',
    status: 'Active',
    salary: 148000,
    joinDate: '2022-11-15',
    skills: ['SEO/SEM', 'Content Strategy', 'HubSpot', 'B2B Inbound', 'Brand PR'],
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=256&q=80',
    performanceScore: 93,
  },
  {
    id: 'emp-7',
    name: 'David Sterling',
    email: 'david.sterling@enterprise.ai',
    phone: '+1 (555) 890-1237',
    departmentId: 'dept-4',
    departmentName: 'Enterprise Sales',
    role: 'Enterprise Sales Director',
    status: 'Active',
    salary: 160000,
    joinDate: '2021-09-01',
    skills: ['Key Account Management', 'CRM', 'Negotiation', 'Revenue Forecasting'],
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=256&q=80',
    performanceScore: 95,
  },
  {
    id: 'emp-8',
    name: 'Amara Okafor',
    email: 'amara.okafor@enterprise.ai',
    phone: '+1 (555) 901-2348',
    departmentId: 'dept-4',
    departmentName: 'Enterprise Sales',
    role: 'Senior Account Executive',
    status: 'Remote',
    salary: 115000,
    joinDate: '2023-02-18',
    skills: ['SaaS Demos', 'Outbound Prospecting', 'Salesforce', 'Customer Relations'],
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=256&q=80',
    performanceScore: 88,
  },
  {
    id: 'emp-9',
    name: 'Rachel Green',
    email: 'rachel.green@enterprise.ai',
    phone: '+1 (555) 012-3459',
    departmentId: 'dept-5',
    departmentName: 'Human Resources & Talent',
    role: 'Director of People & Culture',
    status: 'Active',
    salary: 130000,
    joinDate: '2022-04-10',
    skills: ['Talent Acquisition', 'Labor Compliance', 'DEI', 'Performance Review'],
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=256&q=80',
    performanceScore: 92,
  },
  {
    id: 'emp-10',
    name: 'Arthur Pendelton',
    email: 'arthur.p@enterprise.ai',
    phone: '+1 (555) 123-4560',
    departmentId: 'dept-6',
    departmentName: 'Finance & Operations',
    role: 'Financial Controller',
    status: 'Active',
    salary: 142000,
    joinDate: '2022-01-20',
    skills: ['Financial Modeling', 'Audit', 'ERP', 'Budget Allocation', 'Tax Compliance'],
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=256&q=80',
    performanceScore: 90,
  },
  {
    id: 'emp-11',
    name: 'Chloe Dubois',
    email: 'chloe.dubois@enterprise.ai',
    phone: '+1 (555) 234-5672',
    departmentId: 'dept-1',
    departmentName: 'Engineering & Technology',
    role: 'DevOps & Security Specialist',
    status: 'On Leave',
    salary: 128000,
    joinDate: '2023-07-01',
    skills: ['Terraform', 'CI/CD', 'Security Hardening', 'Docker', 'Monitoring'],
    avatar: 'https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&w=256&q=80',
    performanceScore: 87,
  },
  {
    id: 'emp-12',
    name: 'Kavita Patel',
    email: 'kavita.patel@enterprise.ai',
    phone: '+1 (555) 345-6783',
    departmentId: 'dept-2',
    departmentName: 'Product & Design',
    role: 'Product Operations Analyst',
    status: 'Active',
    salary: 98000,
    joinDate: '2023-09-15',
    skills: ['SQL', 'Tableau', 'User Telemetry', 'Customer Journeys'],
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=256&q=80',
    performanceScore: 94,
  },
];

export const initialProjects: Project[] = [
  {
    id: 'proj-1',
    name: 'Enterprise Cloud Migration v4',
    code: 'ECM-2026',
    description: 'Transition of legacy microservices into multi-region hybrid Kubernetes clusters with zero downtime.',
    departmentId: 'dept-1',
    departmentName: 'Engineering & Technology',
    managerId: 'emp-1',
    managerName: 'Alexander Wright',
    teamMemberIds: ['emp-1', 'emp-2', 'emp-3', 'emp-11'],
    status: 'Active',
    progress: 74,
    budget: 350000,
    startDate: '2026-02-01',
    deadline: '2026-11-30',
    riskLevel: 'Low',
  },
  {
    id: 'proj-2',
    name: 'AI Enterprise Intelligence Assistant',
    code: 'AIE-CORE',
    description: 'Autonomous AI workflow copilot with enterprise memory, document indexing, and predictive resource allocation.',
    departmentId: 'dept-1',
    departmentName: 'Engineering & Technology',
    managerId: 'emp-2',
    managerName: 'Sarah Jenkins',
    teamMemberIds: ['emp-2', 'emp-3', 'emp-5', 'emp-12'],
    status: 'Active',
    progress: 82,
    budget: 420000,
    startDate: '2026-03-10',
    deadline: '2026-10-25',
    riskLevel: 'Medium',
  },
  {
    id: 'proj-3',
    name: 'Unified Design System 3.0',
    code: 'UDS-GLO',
    description: 'Component architecture overhaul across Web, iOS, Android, and internal back-office portals.',
    departmentId: 'dept-2',
    departmentName: 'Product & Design',
    managerId: 'emp-4',
    managerName: 'Elena Rostova',
    teamMemberIds: ['emp-4', 'emp-5', 'emp-3'],
    status: 'Active',
    progress: 60,
    budget: 180000,
    startDate: '2026-04-01',
    deadline: '2026-12-15',
    riskLevel: 'Low',
  },
  {
    id: 'proj-4',
    name: 'Global Enterprise Expansion Q4',
    code: 'GEE-2026',
    description: 'Multi-lingual marketing campaigns and regional partner networks in EMEA and APAC.',
    departmentId: 'dept-3',
    departmentName: 'Global Marketing & Brand',
    managerId: 'emp-6',
    managerName: 'Sophia Chang',
    teamMemberIds: ['emp-6', 'emp-7', 'emp-8'],
    status: 'At Risk',
    progress: 45,
    budget: 290000,
    startDate: '2026-05-01',
    deadline: '2026-10-31',
    riskLevel: 'Critical',
  },
  {
    id: 'proj-5',
    name: 'SOC-2 Type II & ISO 27001 Audit',
    code: 'COMP-SEC',
    description: 'Comprehensive compliance certification and automated privacy pipeline verification.',
    departmentId: 'dept-6',
    departmentName: 'Finance & Operations',
    managerId: 'emp-10',
    managerName: 'Arthur Pendelton',
    teamMemberIds: ['emp-10', 'emp-1', 'emp-11'],
    status: 'Active',
    progress: 90,
    budget: 130000,
    startDate: '2026-01-15',
    deadline: '2026-10-20',
    riskLevel: 'Low',
  },
  {
    id: 'proj-6',
    name: 'Talent Onboarding Portal 2.0',
    code: 'HR-ONB',
    description: 'Self-service digital onboarding, compliance tracking, and automated benefit enrollment.',
    departmentId: 'dept-5',
    departmentName: 'Human Resources & Talent',
    managerId: 'emp-9',
    managerName: 'Rachel Green',
    teamMemberIds: ['emp-9', 'emp-5', 'emp-12'],
    status: 'Planning',
    progress: 25,
    budget: 95000,
    startDate: '2026-08-01',
    deadline: '2027-01-30',
    riskLevel: 'Low',
  },
];

export const initialTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Migrate Redis session cache to distributed Valkey cluster',
    description: 'Ensure low-latency session persistence during high concurrency periods.',
    projectId: 'proj-1',
    projectName: 'Enterprise Cloud Migration v4',
    assignedToId: 'emp-1',
    assignedToName: 'Alexander Wright',
    priority: 'High',
    status: 'In Progress',
    progress: 65,
    dueDate: '2026-10-18',
    createdAt: '2026-10-01',
    tags: ['DevOps', 'Caching', 'Cloud'],
  },
  {
    id: 'task-2',
    title: 'Integrate Gemini 3.8 Flash model into Assistant API',
    description: 'Connect server-side LLM endpoint with vector retrieval and enterprise context caching.',
    projectId: 'proj-2',
    projectName: 'AI Enterprise Intelligence Assistant',
    assignedToId: 'emp-2',
    assignedToName: 'Sarah Jenkins',
    priority: 'Urgent',
    status: 'In Progress',
    progress: 85,
    dueDate: '2026-10-12',
    createdAt: '2026-10-02',
    tags: ['AI', 'Backend', 'LLM'],
  },
  {
    id: 'task-3',
    title: 'Audit token consumption & implement rate limit guards',
    description: 'Prevent uncontrolled API spikes and set per-department token allowances.',
    projectId: 'proj-2',
    projectName: 'AI Enterprise Intelligence Assistant',
    assignedToId: 'emp-2',
    assignedToName: 'Sarah Jenkins',
    priority: 'High',
    status: 'To Do',
    progress: 10,
    dueDate: '2026-10-15',
    createdAt: '2026-10-03',
    tags: ['AI', 'Security', 'Cost'],
  },
  {
    id: 'task-4',
    title: 'Develop responsive Enterprise Dashboard cards and chart widgets',
    description: 'Implement dark-mode optimized components with accessibility WCAG AA standards.',
    projectId: 'proj-2',
    projectName: 'AI Enterprise Intelligence Assistant',
    assignedToId: 'emp-3',
    assignedToName: 'Michael Torres',
    priority: 'High',
    status: 'In Progress',
    progress: 90,
    dueDate: '2026-10-10',
    createdAt: '2026-10-01',
    tags: ['Frontend', 'UI/UX'],
  },
  {
    id: 'task-5',
    title: 'Publish accessible Color Palette tokens for Design System 3.0',
    description: 'Ensure contrast ratios across high-contrast themes and embedded client widgets.',
    projectId: 'proj-3',
    projectName: 'Unified Design System 3.0',
    assignedToId: 'emp-5',
    assignedToName: 'Liam Chen',
    priority: 'Medium',
    status: 'Completed',
    progress: 100,
    dueDate: '2026-10-05',
    createdAt: '2026-09-20',
    tags: ['Figma', 'Tokens'],
  },
  {
    id: 'task-6',
    title: 'Finalize APAC Lead Gen Campaign ad copy & landing page translations',
    description: 'Launch synchronized advertising campaign across Tokyo, Singapore, and Sydney hubs.',
    projectId: 'proj-4',
    projectName: 'Global Enterprise Expansion Q4',
    assignedToId: 'emp-6',
    assignedToName: 'Sophia Chang',
    priority: 'Urgent',
    status: 'In Progress',
    progress: 40,
    dueDate: '2026-10-14',
    createdAt: '2026-09-25',
    tags: ['Marketing', 'APAC', 'Growth'],
  },
  {
    id: 'task-7',
    title: 'Review Enterprise SLA agreements with Tier-1 Banking client',
    description: 'Negotiate 99.99% uptime guarantees and dedicated disaster recovery failover.',
    projectId: 'proj-4',
    projectName: 'Global Enterprise Expansion Q4',
    assignedToId: 'emp-7',
    assignedToName: 'David Sterling',
    priority: 'Urgent',
    status: 'In Review',
    progress: 80,
    dueDate: '2026-10-11',
    createdAt: '2026-09-28',
    tags: ['Sales', 'Contracts', 'Legal'],
  },
  {
    id: 'task-8',
    title: 'Conduct external penetration testing for SOC-2 Type II audit',
    description: 'Address any high/medium CVE findings prior to third-party auditor submission.',
    projectId: 'proj-5',
    projectName: 'SOC-2 Type II & ISO 27001 Audit',
    assignedToId: 'emp-1',
    assignedToName: 'Alexander Wright',
    priority: 'High',
    status: 'Completed',
    progress: 100,
    dueDate: '2026-10-04',
    createdAt: '2026-09-15',
    tags: ['Security', 'Audit'],
  },
  {
    id: 'task-9',
    title: 'Prepare automated payroll reconciliation workflow',
    description: 'Automate dual-currency wire transfer calculations with ERP integration.',
    projectId: 'proj-5',
    projectName: 'SOC-2 Type II & ISO 27001 Audit',
    assignedToId: 'emp-10',
    assignedToName: 'Arthur Pendelton',
    priority: 'Medium',
    status: 'Completed',
    progress: 100,
    dueDate: '2026-10-06',
    createdAt: '2026-09-22',
    tags: ['Finance', 'Automation'],
  },
  {
    id: 'task-10',
    title: 'Configure single sign-on (SSO) SAML connector for new hires',
    description: 'Test Okta and Google Workspace federated authentication for Onboarding Portal.',
    projectId: 'proj-6',
    projectName: 'Talent Onboarding Portal 2.0',
    assignedToId: 'emp-3',
    assignedToName: 'Michael Torres',
    priority: 'Medium',
    status: 'To Do',
    progress: 15,
    dueDate: '2026-10-24',
    createdAt: '2026-10-02',
    tags: ['HR', 'Auth', 'SSO'],
  },
  {
    id: 'task-11',
    title: 'Draft Annual Employee Wellness & Benefits Satisfaction Survey',
    description: 'Compile anonymous feedback forms and benchmark against tech industry standards.',
    projectId: 'proj-6',
    projectName: 'Talent Onboarding Portal 2.0',
    assignedToId: 'emp-9',
    assignedToName: 'Rachel Green',
    priority: 'Low',
    status: 'To Do',
    progress: 0,
    dueDate: '2026-11-05',
    createdAt: '2026-10-05',
    tags: ['HR', 'Culture'],
  },
  {
    id: 'task-12',
    title: 'Perform weekly Database index optimization & slow query tuning',
    description: 'Examine query planner logs for task filtering and employee aggregation views.',
    projectId: 'proj-1',
    projectName: 'Enterprise Cloud Migration v4',
    assignedToId: 'emp-1',
    assignedToName: 'Alexander Wright',
    priority: 'Medium',
    status: 'In Progress',
    progress: 50,
    dueDate: '2026-10-16',
    createdAt: '2026-10-03',
    tags: ['Database', 'SQL', 'Performance'],
  },
];

export const initialUsers: User[] = [
  {
    id: 'usr-admin',
    name: 'Admin Director',
    email: 'admin@enterprise.ai',
    role: 'Admin',
    departmentId: 'dept-1',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=256&q=80',
    status: 'Active',
    createdAt: '2024-01-01',
  },
  {
    id: 'usr-manager',
    name: 'Sarah Jenkins',
    email: 'sarah.tech@enterprise.ai',
    role: 'Manager',
    departmentId: 'dept-1',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=256&q=80',
    status: 'Active',
    createdAt: '2024-02-15',
  },
  {
    id: 'usr-employee',
    name: 'Michael Torres',
    email: 'alex.dev@enterprise.ai',
    role: 'Employee',
    departmentId: 'dept-1',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
    status: 'Active',
    createdAt: '2024-03-01',
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Urgent Task Deadline Alert',
    message: 'Task "Integrate Gemini 3.8 Flash model into Assistant API" is due in 5 days (Oct 12).',
    type: 'deadline',
    priority: 'urgent',
    read: false,
    timestamp: '10 minutes ago',
  },
  {
    id: 'notif-2',
    title: 'AI Risk Detection Warning',
    message: 'Project "Global Enterprise Expansion Q4" is trending behind schedule (45% vs 65% target).',
    type: 'risk',
    priority: 'high',
    read: false,
    timestamp: '45 minutes ago',
  },
  {
    id: 'notif-3',
    title: 'New Enterprise Task Assigned',
    message: 'Alexander Wright was assigned "Perform weekly Database index optimization".',
    type: 'task',
    priority: 'normal',
    read: true,
    timestamp: '2 hours ago',
  },
  {
    id: 'notif-4',
    title: 'SOC-2 Compliance Milestone Completed',
    message: 'Audit external penetration testing finished with zero critical vulnerabilities.',
    type: 'system',
    priority: 'low',
    read: true,
    timestamp: '1 day ago',
  },
];

export const initialActivityLogs: ActivityLog[] = [
  {
    id: 'act-1',
    userName: 'Sarah Jenkins',
    userRole: 'Manager',
    action: 'Updated progress to 85%',
    target: 'Task: Integrate Gemini 3.8 Flash model',
    module: 'tasks',
    timestamp: '15 mins ago',
  },
  {
    id: 'act-2',
    userName: 'Admin Director',
    userRole: 'Admin',
    action: 'Ran AI Autonomous Workload Scan',
    target: 'System Automation Center',
    module: 'ai',
    timestamp: '1 hour ago',
  },
  {
    id: 'act-3',
    userName: 'Alexander Wright',
    userRole: 'Employee',
    action: 'Completed task verification',
    target: 'Conduct external penetration testing',
    module: 'tasks',
    timestamp: '3 hours ago',
  },
  {
    id: 'act-4',
    userName: 'Elena Rostova',
    userRole: 'Manager',
    action: 'Modified project timeline',
    target: 'Unified Design System 3.0',
    module: 'projects',
    timestamp: '5 hours ago',
  },
  {
    id: 'act-5',
    userName: 'Admin Director',
    userRole: 'Admin',
    action: 'Added new team member',
    target: 'Kavita Patel (Product Analyst)',
    module: 'employees',
    timestamp: 'Yesterday',
  },
];

export const defaultSettings: SystemSettings = {
  companyName: 'Apex Enterprise Global Inc.',
  contactEmail: 'operations@enterprise.ai',
  workingHours: '09:00 - 18:00 (EST)',
  currency: 'USD ($)',
  aiAutoScan: true,
  aiAutoScanFrequency: 'Daily',
  deadlineAlertThresholdDays: 3,
  workloadThresholdTasks: 4,
  requireTwoFactor: true,
};
